/**
 * Turns detectPatterns() output into first-class, individually addressable
 * rows in elos_patterns — written BY the engine, not typed by a human.
 *
 * Lifecycle (simplified from the ELOS spec's CANDIDATE→DETECTED→VERIFIED→
 * ACTIVE→RETIRED chain, sized for this dataset):
 *   CANDIDATE — pattern detected, below promotion threshold
 *   ACTIVE    — sampleSize >= 5 AND percentage >= 60 (system-promoted)
 *   RETIRED   — was ACTIVE, evidence has since dropped below 30%
 *
 * Every field is derived from the data. Nobody writes prose for this;
 * `statement` is machine-generated by patternEngine.js.
 */
function slugify(str) {
  return String(str)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

function patternIdFor(pattern) {
  if (pattern.scope === "ecosystem") {
    return `AUTO-ECO-${slugify(pattern.weakness)}`;
  }
  return `AUTO-IND-${slugify(pattern.industry)}-${slugify(pattern.weakness)}`;
}

function statusFor(pattern, previousStatus) {
  if (pattern.percentage >= 60 && pattern.sampleSize >= 5) return "ACTIVE";
  if (previousStatus === "ACTIVE" && pattern.percentage < 30) return "RETIRED";
  return "CANDIDATE";
}

/**
 * @param {object} detected - output of intelligence/patternEngine.js detectPatterns()
 * @param {object} existingStatusById - { [pattern_id]: current status in DB }, for promotion history
 * @returns {Array} rows ready to upsert into elos_patterns
 */
function buildAutoPatternRows(detected, existingStatusById = {}) {
  return (detected.patterns || []).map((p) => {
    const pattern_id = patternIdFor(p);
    const status = statusFor(p, existingStatusById[pattern_id]);
    return {
      pattern_id,
      name:
        p.scope === "ecosystem"
          ? `Ecosystem-wide: ${p.weakness}`
          : `${p.industry}: ${p.weakness}`,
      pattern_type: p.scope,
      status,
      confidence: p.percentage,
      data: { ...p, pattern_id, status, autoGenerated: true, lastEvaluatedAt: detected.generatedAt },
    };
  });
}

module.exports = { buildAutoPatternRows, patternIdFor };
