const { applyCors } = require("./_lib/cors");
const store = require("./_lib/supabase");

// Read-only. ACTIVE/REJECTED/HISTORICAL principles are the human-confirmed
// ones migrated from the original field-trial documentation (03_pattern_intelligence
// era). EXPERIMENTAL principles with data.autoGenerated=true were drafted by
// the engine itself (api/outcomes.js -> proposePrincipleIfWarranted) from
// repeated negative outcomes — flagged for review, not written by a human.
module.exports = async function handler(req, res) {
  if (applyCors(req, res)) return;
  if (req.method !== "GET") {
    res.status(405).json({ error: "Only GET allowed" });
    return;
  }
  const principles = await store.listPrinciples();
  res.status(200).json({ total: principles.length, principles });
};
